FROM golang:1.17rc1-alpine

WORKDIR /backend

RUN apk update && apk add curl

COPY go.mod ./

RUN go mod download

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s && \
    chmod +x install.sh && \
    sh install.sh && \
    cp ./bin/air /bin/air

COPY . .

RUN air init

RUN go run main.go

CMD [ "air", "-d" ]

